'use strict';
const express = require('express');
const { authenticateToken } = require('../middleware/auth');
const { deleteMailboxMessage, downloadMailboxAttachment, getMailboxMessage, listMailbox, replyToMailboxMessage } = require('../controllers/mailboxController');
const router = express.Router();
router.use(authenticateToken);
router.get('/inbox', listMailbox);
router.post('/inbox/:id/reply', replyToMailboxMessage);
router.delete('/inbox/:id', deleteMailboxMessage);
router.get('/inbox/:id/attachments/:attachmentId/download', downloadMailboxAttachment);
router.get('/inbox/:id', getMailboxMessage);
module.exports = router;
